spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/vault
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    enabled: true

application:
  storage:
    root: './storage'